### PR TITLE
Fix none filter for numeric field

### LINKED ISSUE #2399: [BUG] Fix None filter for numeric fields
The `None` selector is not appearing and functioning correctly in all cases.

## Example

For example, below both the `predictions.detections.confidence` and `uniqueness` fields of `view` have some missing values:

```py
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset("quickstart")

some_nones = lambda field: (F(field) < 0.5).if_else(None, F(field))
view = (
    dataset
    .set_field("predictions.detections.confidence", some_nones("confidence"))
    .set_field("uniqueness", some_nones("uniqueness"))
)

session = fo.launch_app(view)
```

**State A**: when I open the filter widget for `predictions.detections.confidence` initially, I see:
Screen Shot 2022-12-06 at 9 39 46 AM

**State B**: if I then drag the 0.5 slider to the right and then all the way back left, I then see:
Screen Shot 2022-12-06 at 9 39 57 AM

**C**: if I then uncheck the `None` field, I see this:
Screen Shot 2022-12-06 at 9 40 06 AM

## Option 1

One way to make the behavior consistent would be the following:
- In State A, `[x] None: 4056` should appear by default, since the grid is showing all 5620 boxes, including the 4056 that have `confidence == None`
- In State B, `[x] None` should not be checked, since we are only seeing `1,564 of 5,620` objects in the grid, which excludes all objects with `confidence == None`

The tricky thing here (and I believe the reason that things are inconsistent to begin with), is that, if the user adjusts the numeric slider's endpoints, then they probably do not want to see None-valued items too, so we were trying to save the user a click by automatically also omitting `None` values when the slider has been used. This leads me to second option:

## Option 2 (let's use this one?)

Only show the `[ ] None` filter if the slider's endpoints are in their default states (fully extended).

This would imply:
- If the slider is in the default location, allow the user to toggle whether `None` values are included or not, with the default being `[x] None`, since we don't filter anything by default and thus the `None` values are in fact included
- If the slider is in a non-default location, automatically omit `None` values, and visually convey this to the user by hiding the `[ ] None` filter altogether
    - This means that a user would *not* be able to ask for all values in `[a, b]` or `None`, but that's okay because they can do that through code if they really want to, and we also do not allow, for example, asking for values in `[a, b]` or `[c, d]` through the filter widget, for example

One additional detail: if the field contains zero `None` values, then hide the `[ ] None` filter altogether, even in the default state, since it would never offer any useful filtering capability (I think this is already the case, just confirming to keep it).

### PR DESCRIPTION
**Pull request by lanzhenw**
fixes #2399 
## What changes are proposed in this pull request?

https://user-images.githubusercontent.com/17770824/206592972-a68968a7-990d-480a-8fca-b97dc1a1b14d.mov

## How is this patch tested? If it is not, please explain why.

(Details)

### Is this a user-facing change that should be mentioned in the release notes?

-   [x] No. You can skip the rest of this section.
-   [ ] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

(Details in 1-2 sentences. You can just refer to another PR with a description
if this PR is part of a larger change.)

### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

File: app/packages/core/src/components/Filters/NumericFieldFilter.tsx [hunk 1]
```diff
@@ -157,6 +164,12 @@ const NumericFieldFilter = ({
     (nonfinites.length === 1 && nonfinites[0][0] === "none")
   );
 
+  const hasNone =
+    nonfinites.some((x) => x[0] === "none") &&
+    nonfinites.find((x) => x[0] === "none")![1].count !== 0;
+  const isSliderAtInitialPostion =
+    bounds[0] === values[0] && bounds[1] === values[1];
```
Comment (benjaminpkane) [inline app/packages/core/src/components/Filters/NumericFieldFilter.tsx:171]: `isSliderAtInitialPosition` and `hasDefaultRange` should mean the same thing. Maybe you can fix the `isDefaultRange` selector?

File: app/packages/core/src/components/Filters/NumericFieldFilter.tsx [hunk 2]
```diff
@@ -238,9 +251,7 @@ const NumericFieldFilter = ({
           />
         ) : null}
         {(hasDefaultRange ||
-          nonfinites.some(
-            ([_, { value: v }]) => v !== nonfinites[0][1].value
-          ) ||
+          (hasNone && isSliderAtInitialPostion) ||
```
Comment (benjaminpkane) [inline app/packages/core/src/components/Filters/NumericFieldFilter.tsx:254]: If `isSliderAtInitialPosition` and `hasDefaultRange` have the same definition then this could become:
```js
        {(hasNone && hasDefaultRange) ||
```

File: app/packages/core/src/components/Filters/NumericFieldFilter.tsx [hunk 3]
```diff
@@ -157,6 +164,12 @@ const NumericFieldFilter = ({
     (nonfinites.length === 1 && nonfinites[0][0] === "none")
   );
 
+  const hasNone =
+    nonfinites.some((x) => x[0] === "none") &&
+    nonfinites.find((x) => x[0] === "none")![1].count !== 0;
```
Comment (benjaminpkane) [inline app/packages/core/src/components/Filters/NumericFieldFilter.tsx:169]: Based on the implementation of `useNonfinites` empty counts are already filtered:
```suggestion
  const hasNone = nonfinites.some((x) => x[0] === "none")
```

File: app/packages/core/src/components/Filters/NumericFieldFilter.tsx (hunk 1 above)
Comment (lanzhenw) [reply app/packages/core/src/components/Filters/NumericFieldFilter.tsx:169]: I will fix `hasDefaultRange` and name is `isDefaultRange`. I wasn't sure about `hasDefaultRange` so didn't touch it.

**Review by benjaminpkane — APPROVED** [review]
LGTM!
