### PR TITLE
Fix #4890

### LINKED ISSUE #4890: [BUG] `fo.Classifications` labels aren't displayed in UI in v1.0.0
### Describe the problem

It seems `fo.Classifications` fields aren't displayed in the UI from v1.0.0 (they were correctly displayed in v0.25.2).
image
From the code snippet below, we should see "three" and "four" on the sample.

From looking at [the release note for v1.0.0](https://docs.voxel51.com/release-notes.html#fiftyone-1-0-0), I guess the culprit would be https://github.com/voxel51/fiftyone/pull/4747

### Code to reproduce issue

```python
import fiftyone as fo

dataset = fo.load_dataset("tmp_dataset_laurent")
for sample in dataset:
    sample["classification1"] = fo.Classification(label="one")
    sample["classification2"] = fo.Classification(label="two")
    sample["classifications1"] = fo.Classifications(classifications=[fo.Classification(label="three")])
    sample["classifications2"] = fo.Classifications(classifications=[fo.Classification(label="four")])
    sample.save()
```

### System information

-   **OS Platform and Distribution**: Ubuntu 24.04 LTS
-   **Python version**: Python 3.10.14
-   **FiftyOne version**: FiftyOne v1.0.0
-   **FiftyOne installed from**: [rye](https://github.com/astral-sh/rye) (which uses [uv](https://github.com/astral-sh/uv))

### Willingness to contribute

-   [ ] Yes. I can contribute a fix for this bug independently
-   [ ] Yes. I would be willing to contribute a fix for this bug with from the FiftyOne community
-   [x] No. I cannot contribute a bug fix at this time

### PR DESCRIPTION
**Pull request by benjaminpkane**
## What changes are proposed in this pull request?

Resolves #4890

```python
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart-video", max_samples=1)

sample = dataset.first()
sample["classes"] = fo.Classifications(classifications=[fo.Classification(label="class")])
sample["detections"] = fo.TemporalDetections(detections=[fo.TemporalDetection(label="detection")])
sample.save()

session = fo.launch_app(dataset)
``` 
Screenshot 2024-10-04 at 10 42 39 AM

## How is this patch tested? If it is not, please explain why.

Unit tests for the  `Classifications` and `TemporalDetections` special cases

## Release Notes

* Fixed |Classifications| and |TemporalDetections| grid rendering

### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

## Summary by CodeRabbit

- **New Features**
	- Enhanced handling of classifications and temporal detections in bubble processing.
  
- **Bug Fixes**
	- Improved functionality of the `getBubbles` function to correctly process nested data structures. 

- **Tests**
	- Expanded test coverage for the `getBubbles` function with new scenarios for classifications and temporal detections.

### CODE REVIEW

File: app/packages/looker/src/elements/common/bubbles.ts [hunk 1]
```diff
@@ -54,14 +54,14 @@ export const getBubbles = (
     }
 
     if (field.embeddedDocType === withPath(LABELS_PATH, CLASSIFICATIONS)) {
-      out.values = out.values.flatMap(
+      out.values = unwind(field.dbField, out.values).flatMap(
```
Comment (kaixi-wang) [inline app/packages/looker/src/elements/common/bubbles.ts:57]: What does out.values look like? Flat map should unnest arrays so it's weird that you would need to unwind first

Comment (benjaminpkane) [reply app/packages/looker/src/elements/common/bubbles.ts:57]: out.values is a list or single value of potentially renderable field data. flatMap flattens the nested `classifications`

**Review by sashankaryal — APPROVED** [review]
lgtm!
